[build]
  dockerfile = "Dockerfile"

[deploy]
  healthcheckPath = "/"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  command = "n8n start"  # Cambio clave: usa `command` en lugar de `startCommand`

[service]
  name = "n8n"
  internal_port = 5678
  disk = [
    { mountPath = "/home/node/.n8n", sizeGB = 1 }
  ]
