[build]
  dockerfile = "Dockerfile"

[deploy]
  healthcheckPath = "/"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  startCommand = "n8n start"

[service]
  name = "n8n"
  internal_port = 5678

#  Essential variables that must be defined in Railway UI or Secrets
#  N8N_EDITOR_BASE_URL = ""
#  N8N_PROTOCOL = "https"