[build]
  dockerfile = "Dockerfile"

[deploy]
  healthcheckPath = "/"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  startCommand = "n8n start"   # <-- STRING literal obligatorio para Railway

[service]
  name = "n8n"
  internal_port = 5678
  disk = [
    { mountPath = "/home/node/.n8n", sizeGB = 1 }
  ]
