[build]
  dockerfile = "Dockerfile"

[deploy]
  healthcheckPath = "/"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"

[service]
  name = "n8n"
  internal_port = 5678
  disk = [
    { mountPath = "/home/node/n8n-data", sizeGB = 1 }
  ]
  startCommand = ["n8n"]
